### ISSUE TITLE
Change pressure to Inches

### ISSUE THREAD

**Issue by bnelson796** [liu044100/SmileWeather#3]
How would you change the pressure to inches of mercury?

**Comment by liu044100** [comment]
I have pushed a new version [0.1.5](https://github.com/liu044100/SmileTouchID/releases/tag/0.1.5) to cocoapods, that give the `SmileWeatherCurrentData` a new property `pressure_mercuryInch`.

``` Objective-c
SmileWeatherData *data = ...
data.currentData.pressure_mercuryInch = ...
```

**Comment by Zero-zhou** [comment]
/BuildRoot/Library/Caches/com.apple.xbs/Sources/ProtocolBuffer_Sim/ProtocolBuffer-242/Runtime/PBRequester.m:807 server (https://gsp13-cn.ls.apple.com/localshift) returned error: 500
2015-12-02 09:03:27.913 Smile Weather[5496:40623] error -> The operation couldn’t be completed. (kCLErrorDomain error 2.)

**Comment by liu044100** [comment]
Hello, @Zero-zhou, could you give me more detail or a example project?

**Comment by Zero-zhou** [comment]
@liu044100  I'm sorry, there has been no attention. This problem has been solved,Thank you。
