### ISSUE TITLE
ForecastDayData pressure is missing

### ISSUE THREAD

**Issue by skuske** [liu044100/SmileWeather#5]
Any reason why ForecastDayData does not include the pressure data?

**Comment by liu044100** [comment]
Hi, @skuske 

There is no special reason for it... 😬

`SmileWeatherCurrentData` has many detail info including the pressure data,  you can refer this class and extend `SmileWeatherForecastDayData`.

Sorry for that I hasn't enough time to make data model better.

**Comment by skuske** [comment]
:) No problem. I thought there was a special reason as the current data includes pressure...

**Comment by liu044100** [comment]
Hi, @skuske 

This is a JSON file that get from openweathermap, hope this could help you. 😁

https://github.com/liu044100/SmileWeather/blob/master/SmileWeather-Example/SmileWeather-ExampleTests/SampleResponse.json
