### ISSUE TITLE
NSAppTransportSecurity issue, use https for API calls.

### ISSUE THREAD

**Issue by alexruperez** [liu044100/SmileWeather#7]

**Comment by liu044100** [comment]
Hi, @alexruperez 

Thanks for your advice.

As long as I know, [OpenWeatherMap](http://openweathermap.org/current) is only http.

 [Wunderground](https://www.wunderground.com/weather/api/d/docs) seems have adopted https, when I access [this sample api](https://api.wunderground.com/api/d8483e016960a875/conditions/q/CA/San_Francisco.json).

I will update Wunderground related code later.

**Comment by liu044100** [comment]
Solved: https://github.com/liu044100/SmileWeather/pull/8
